### ISSUE TITLE
Incorrect locking threshold range for new iteration. 

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/votemvp#1]
22/3/22 votemvp Version = 0.1.3mvp, Iteration = 8
Exchangerate table CP=0.01000000000000000 TP=0.02066666666666667 (voted locking threshold at end of iter 7) 
The locking threshold max value is incorrect for iteration 8. Expecting the locking threshold range to be  0.0167 - 0.04134 (lockfactor * TP = 2*0.02067) but system showing as 0.0167-0.03340.
1. Test min limits by entering locking threshold of 0.0165 below the min value. Vote rejected which is correct but message was showing incorrect range of 0.0167-0.03340. Expecting the range to be 0.0167-0.4134 based on the updated target value. 
2. Test max limits by entering locking threshold of 0.04135 above the max value, got the same message.
3. Test within limits by entering locking threshold of 0.04134 equal to max value, got the same message.

![Account - Proton Testnet 22-03-2022 11-35-16](https://user-images.githubusercontent.com/77765830/159377602-cbc172ab-f92b-4a5d-9524-ab4320ade3e9.png)
![Account - Proton Testnet 22-03-2022 12-00-22](https://user-images.githubusercontent.com/77765830/159378554-706f0884-bc8d-4dfd-9395-87c758ba70f8.png)
![Account - Proton Testnet 22-03-2022 12-00-48](https://user-images.githubusercontent.com/77765830/159378570-024f42c9-b907-4681-a5df-872bafbf8d84.png)

**Comment by tommccann777** [comment]
My understanding is that the upper limit is calculated by ( lockfactor * current_price )

**Comment by judytan21** [comment]
23/3/22 Following discussion with Tom and JeromeK, the max value is calc based on the hard_exchange_rate_floor and not the target price. The hard_exchange_rate_floor is hardcoded in the code and set at 0.0167. 
This is how the code does it:
if (current_price < HARD_EXCHANGE_RATE_FLOOR) {
        locking_threshold_upper_limit = lock_factor * HARD_EXCHANGE_RATE_FLOOR;
    } else {
        locking_threshold_upper_limit = lock_factor * current_price;
    }

lockfactor is configurable and is currently set to 2.0
