### ISSUE TITLE
VoteMVP Frontend: Manually entered amount text box did not reflect the selected locking threshold value on the slider.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/votemvp#10]
16/5/22 AirClaim Votemvp Frontend v0.5.8qa5 Link: https://tjrhs-gqaaa-aaaad-qa24a-cai.raw.ic0.app
Regression test to ensure vivvestin type 'v' can vote successfully.
Steps:
1. Login as vivvestin.
2. Claim page, select Vote 
3. Vote Locking threshold page, slider showing min 0.0167, max 0.0334 and default 0.02505. Manually entered amount box was also showing as the default value of 0.02505. Correct.
4. Move slider to max value to vote for 0.0334. Manually entered amount text box was still showing as 0.02505. Expecting the amount text box to show 0.0334 when the slider was moved to max value.
5. Submit vote. Successful but the woohoo msg shows 0.02505 as the voted amount instead of the selected 0.0334 selected on the slider. 
![Freeos App 16-05-2022 12-03-51](https://user-images.githubusercontent.com/77765830/168500602-55b0c890-5089-44b7-ba7d-ef6aebefb708.png)

Here's another example-> user jamiejackson with an Airkey.
![Freeos App 16-05-2022 16-20-26](https://user-images.githubusercontent.com/77765830/168519742-f2bb9b57-ba42-4f31-adb3-ca2da25b8894.png)
![Freeos App 16-05-2022 16-21-17](https://user-images.githubusercontent.com/77765830/168519753-da99c719-c6c7-43ad-8d1e-25fc6cf40911.png)

**Comment by sjmcpherson** [comment]
This is fixed in v0.5.9

**Comment by judytan21** [comment]
30/5/22 AirClaim Votemvp Frontend v0.5.10qa5 Link: https://tjrhs-gqaaa-aaaad-qa24a-cai.raw.ic0.app/
Retest using alanappleton with type 'e' user with 1 Airkey.
Move slider to value 0.031898. Manually entered amount text box was updated to 0.031898. Vote submitted successfully for iteration 19. Fixed.
