### ISSUE TITLE
VoteMVP frontend: Missing locking threshold range on slider.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/votemvp#3]
5/4/22 AirClaim Votemvp Frontend v0.5.2qa5 Link: https://tjrhs-gqaaa-aaaad-qa24a-cai.raw.ic0.app/vote
On the Vote Locking Threshold page, the locking threshold values were missing on the slider.
Steps.
1. Login as vivvestin, account type 'v'.
2. On Claim page, click on 'Go to Vote'.
3. Taken to Vote Locking Threshold page, locking threshold values missing on the slider.
4. Expecting locking threshold range to be 0.016700-0.033400 (Tom said to show the min/max values up to 6 dec places).
![Freeos App 05-04-2022 13-58-41](https://user-images.githubusercontent.com/77765830/161665223-6e525e35-17ea-47fd-8818-67332789829f.png)

**Comment by stuartmcphersonflipmind** [comment]
Changed v0.5.4

**Comment by judytan21** [comment]
6/4/22 Retest in v0.5.4-qa5. 
On Vote Locking Threshold page, min and max values should be displayed on each end of the slider control  prior to clicking on the slider so the user knows what the locking threshold is. Locking threshold values must be displayed with 6 decimal places. Also, there is a blue dot on the left hand side of the page which needs to be removed. Not fixed.

![Freeos App 06-04-2022 15-41-53](https://user-images.githubusercontent.com/77765830/161892141-9ef4ea77-9eb7-4610-a40d-39fbd944453b.png)

**Comment by judytan21** [comment]
11/4/22 Retest in v0.5.4-qa5 after clearing cache in Chrome. Still the same results. 
Stuart, as you reckon it may be account related, I've retested with both Vivvestin and billbeaumont accounts in iteration 14 and the results were the same. 
![Freeos App 11-04-2022 10-59-04](https://user-images.githubusercontent.com/77765830/162643593-c837c620-5705-426b-b29c-242bbca26ad5.png)
![Freeos App 11-04-2022 11-01-46](https://user-images.githubusercontent.com/77765830/162643668-2b97bcf6-4b56-4ac3-8699-e5407f05d2a5.png)

**Comment by stuartmcphersonflipmind** [comment]
Hmm I suspect now that the project is not being built successfully on that server, I will follow up with Tom

**Comment by judytan21** [comment]
11/4/22 Hey Stuart! JeromeK has confirmed all locking threshold value must be in 6 decimal places.
Jerome | freeos.io | freedao.io — Today at 12:33
6…. although I’m not fond of having that many decimals in the UI
But we have to be accurate

**Comment by judytan21** [comment]
19/4/22 Retest in new rel v0.5.5-qa5 using billbeaumont's account in iteration 16. 
On Vote Locking Threshold page, min and max values were displayed on each end of the slider control prior to clicking on the slider so the user knows what the locking threshold range is. Locking threshold values were displayed with 6 decimal places where appropriate i.e. trailing zeroes omitted. This means that the default locking threshold ranges were showing as 0.0167 and 0.04 accordingly. Also, blue dot on the left hand side of the page is no longer showing. 
**Note: 19/4/22 JK is happy with the omission of trailing zeroes when displaying the locking threshold amounts.** 
Issue fIxed. Closed.
![Freeos App 19-04-2022 10-57-37](https://user-images.githubusercontent.com/77765830/163892601-11bf4229-63bf-476e-b421-6333bad523f7.png)
