### ISSUE TITLE
VoteMVP Frontend: small wording change

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/votemvp#4]
5/4/22 AirClaim Votemvp Frontend v0.5.2qa5 Link: [https://tjrhs-gqaaa-aaaad-qa24a-cai.raw.ic0.app](https://tjrhs-gqaaa-aaaad-qa24a-cai.raw.ic0.app/vote)
On the 'Vote on Locking Threshold' page, change wording "Or manually add amount" to "Or manually enter amount".

![Freeos App 05-04-2022 13-58-41](https://user-images.githubusercontent.com/77765830/161676402-fd454a71-fdde-486d-a71d-79b181851420.png)

**Comment by stuartmcphersonflipmind** [comment]
Changed v0.5.4

**Comment by judytan21** [comment]
6/4/22 Retest in v0.5.4-qa5. Wordings corrected. Fixed. Issue closed.
![Freeos App 06-04-2022 16-21-15](https://user-images.githubusercontent.com/77765830/161895119-ecf2cba1-df10-4cf1-b183-5410d9cd85fe.png)
