### ISSUE TITLE
VoteMVP Frontend: Remove tooltip.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/votemvp#5]
5/4/22 AirClaim Votemvp Frontend v0.5.2qa5 Link: [https://tjrhs-gqaaa-aaaad-qa24a-cai.raw.ic0.app](https://tjrhs-gqaaa-aaaad-qa24a-cai.raw.ic0.app/vote)
On the 'Vote on Locking Threshold' page, remove the message ''Please enter a valid value. The two nearest values are 0 and 1" displayed when hovering over the amount entered. (Tom reckons it is not required). 

<img width="889" alt="Screen Shot 2022-04-05 at 4 08 55 PM" src="https://user-images.githubusercontent.com/77765830/161677226-983d0fbc-1165-4024-9160-30f5bab76f65.png">

**Comment by stuartmcphersonflipmind** [comment]
Removed Validation tooltip v0.5.4

**Comment by judytan21** [comment]
6/4/22 Retest in v0.5.4-qa5. Tooltip still showing when hovering over the amount entered. Not fixed.

<img width="891" alt="Screen Shot 2022-04-06 at 4 11 19 PM" src="https://user-images.githubusercontent.com/77765830/161894310-dc1f08fe-46db-48d0-a46e-99eb9ec5dfc0.png">

**Comment by stuartmcphersonflipmind** [comment]
Im not getting this now in the browsers Ive tested Mac Chrome & Safari, what is the browser your using?

**Comment by judytan21** [comment]
11/4/22 Retest in v0.5.4-qa5 using Mac Chrome. Cleared cache. Not seeing the tooltip when hovering over the amount.   Looks like clearing the cache works. 
Also tested in mac safari and it's working fine. Fixed. Close.
![Freeos App 11-04-2022 11-17-09](https://user-images.githubusercontent.com/77765830/162644312-4c2a94e7-52c0-4465-a2af-acf58bc3f68d.png)

**Comment by judytan21** [comment]
11/4/22 Reopening this issue as tooltip still showing when hovering over the amount entered in new rel 0.5.4-qa5ii
account-vivvestin, browser-chrome
<img width="891" alt="Screen Shot 2022-04-11 at 2 33 33 PM" src="https://user-images.githubusercontent.com/77765830/162655931-cfdd988a-6380-4036-8242-937e61946b0e.png">
Repeat test with alanappleton, tooltip still appeared
<img width="891" alt="Screen Shot 2022-04-11 at 2 45 50 PM" src="https://user-images.githubusercontent.com/77765830/162657033-06ffd5d3-422f-4181-b289-09ce10216afb.png">
.

**Comment by judytan21** [comment]
19/4/22 Retest in new rel v0.5.5-qa5. Tooltip still showing when hovering over the amount entered in iteration 16. 
Account-billbeaumont, browser-chrome.
<img width="891" alt="Screen Shot 2022-04-19 at 10 58 35 AM" src="https://user-images.githubusercontent.com/77765830/163890547-4c7a86cd-5d55-481d-8e17-c0555e9e3fac.png">

**Comment by judytan21** [comment]
20/4/22 Retest in new rel v0.5.6-qa5. Tooltip no longer displayed when hovering over the amount entered in iteration 17.
Account-alanappleton, browser-chrome. Fixed. Close.
![Freeos App 20-04-2022 11-01-29](https://user-images.githubusercontent.com/77765830/164115404-96072b5a-6d9e-43e7-9a44-8d79eaf7f007.png)
.
