### ISSUE TITLE
VoteMVP Frontend: Vote slider control does not default to the expected min/max values

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/votemvp#6]
5/4/22 AirClaim Votemvp Frontend v0.5.2qa5 Link: https://tjrhs-gqaaa-aaaad-qa24a-cai.raw.ic0.app/vote
On the Vote Locking Threshold page, the slider control does not default to the expected min/max values. 
Default showing as 0.017-0.025. Current Price in exchagerate table is 0.01300149144607182. Hence, expecting range to be 0.016700-0.033400. 

To work out the max threshold value:
f (current_price < HARD_EXCHANGE_RATE_FLOOR of 0.0167) {
        locking_threshold_upper_limit = lock_factor * HARD_EXCHANGE_RATE_FLOOR;
    } else {
        locking_threshold_upper_limit = lock_factor * current_price;
    }
lockfactor is configurable and is currently set to 2.0

![Freeos App 05-04-2022 16-24-01](https://user-images.githubusercontent.com/77765830/161679747-a49632c2-5742-48e2-8aa8-bf82e28bc250.png)
![Freeos App 05-04-2022 16-23-43](https://user-images.githubusercontent.com/77765830/161679755-1e23decc-1270-40dd-96e4-8fef3ec00c7e.png)

**Comment by stuartmcphersonflipmind** [comment]
Changed vote range to be in steps of "0.0001" so range is 0.0167-0.0334 also with changes from calc v0.5.4

**Comment by judytan21** [comment]
6/4/22 Retest in v0.54-qa5. Slider control defaults to the expected min/max value of 0.016700-0.033400. I can see the steps in increments of 0.0001. However, Tom wanted all locking threshold values to be in 6 decimal places. If that's not possible, please have a chat with Tom. Will keep this open for now.

![Freeos App 06-04-2022 16-26-53](https://user-images.githubusercontent.com/77765830/161896018-62214bc6-913b-4948-a646-32f35b948d24.png)
![Freeos App 06-04-2022 16-27-52](https://user-images.githubusercontent.com/77765830/161896030-1cc2557f-f273-40d8-924f-e4386356f6cd.png)
.

**Comment by judytan21** [comment]
11/4/22 Retest in v0.5.4-qaii. Slider control now defaults to the correct min/max locking threshold values. However, all locking threshold values must be in 6 decimal places. See JeromeK's confirmation below:
Jerome | freeos.io | freedao.io — Today at 12:33
6…. although I’m not fond of having that many decimals in the UI
But we have to be accurate

**Comment by judytan21** [comment]
19/4/22 Retest in new rel v0.5.5-qa5 using billbeaumont's account in iteration 16.
On Vote Locking Threshold page, min and max values were displayed on each end of the slider control prior to clicking on the slider so the user knows what the locking threshold range is. Locking threshold values were displayed with 6 decimal places where appropriate i.e. trailing zeroes omitted. This means that the default locking threshold ranges were showing as 0.0167 and 0.04 accordingly. Also, blue dot on the left hand side of the page is no longer showing.
Note: 19/4/22 JK is happy with the omission of trailing zeroes when displaying the locking threshold amounts.
Issue fIxed. Closed.
![Freeos App 19-04-2022 10-57-37](https://user-images.githubusercontent.com/77765830/163893090-eee2a0c7-67d4-4379-b11e-cbe20828343d.png)
