### ISSUE TITLE
VoteMVP Frontend: Spelling mistake and voted threshold value shown in Point instead of USD.

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/votemvp#7]
5/4/22 AirClaim Votemvp Frontend v0.5.2qa5 Link: https://tjrhs-gqaaa-aaaad-qa24a-cai.raw.ic0.app/vote
On the Vote Locking Threshold page, entered an amount of 0.0240 and click 'Submit Vote'.
Woohoo! pop up displayed but "Thanks for voting!" was misspelt as "Thaks for voting!" (missing letter n).
Also, the voted locking threshold of 0.024 should be in USD, not Point.

<img width="889" alt="Screen Shot 2022-04-05 at 5 01 25 PM" src="https://user-images.githubusercontent.com/77765830/161682214-c4db16d9-7a24-43d6-945e-9b2be7ac42a8.png">
.

**Comment by stuartmcphersonflipmind** [comment]
Fixed v0.5.4

**Comment by judytan21** [comment]
6/4/22 Retest in v0.5.4-qa5. Spelling mistake corrected. Fixed. Issue Closed.
<img width="891" alt="Screen Shot 2022-04-06 at 4 45 35 PM" src="https://user-images.githubusercontent.com/77765830/161898023-40dc46df-cc59-4e70-8479-9af9995add62.png">
